// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cloudscribe.PwaKit.Storage.EFCore.MSSQL;

namespace cloudscribe.PwaKit.Storage.EFCore.MSSQL.Migrations
{
    [DbContext(typeof(PwaDbContext))]
    partial class PwaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("cloudscribe.PwaKit.Models.PushDeviceSubscription", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Auth");

                    b.Property<string>("CreatedFromIpAddress");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("Endpoint");

                    b.Property<string>("P256DH");

                    b.Property<string>("TenantId")
                        .HasMaxLength(50);

                    b.Property<string>("UserAgent");

                    b.Property<string>("UserId")
                        .HasMaxLength(50);

                    b.HasKey("Key");

                    b.HasIndex("Endpoint");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("cspwa_PushSubscription");
                });
#pragma warning restore 612, 618
        }
    }
}
