// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using cloudscribe.PwaKit.Storage.EFCore.PostgreSql;

#nullable disable

namespace cloudscribe.PwaKit.Storage.EFCore.PostgreSql.Migrations
{
    [DbContext(typeof(PwaDbContext))]
    [Migration("20221118105313_cs-pwakit-timestamp")]
    partial class cspwakittimestamp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("cloudscribe.PwaKit.Models.PushDeviceSubscription", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("key");

                    b.Property<string>("Auth")
                        .HasColumnType("text")
                        .HasColumnName("auth");

                    b.Property<string>("CreatedFromIpAddress")
                        .HasColumnType("text")
                        .HasColumnName("created_from_ip_address");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Endpoint")
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<string>("P256DH")
                        .HasColumnType("text")
                        .HasColumnName("p256_dh");

                    b.Property<string>("TenantId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.HasKey("Key")
                        .HasName("pk_cspwa_push_subscription");

                    b.HasIndex("Endpoint")
                        .HasDatabaseName("ix_cspwa_push_subscription_endpoint");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_cspwa_push_subscription_tenant_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_cspwa_push_subscription_user_id");

                    b.ToTable("cspwa_push_subscription", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
